Image:
  Width: 320
  Height: 224



Train:
  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented"
  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented_mask"

  Epoch: 50
  Batch_Size: 8

  # Default: 'EfficientUnet'
  # ['EfficientUnet', 'EfficientUnet3Plus_5', 'EfficientUnet3Plus_7']
  Model_Used: 'EfficientUnet3Plus_7'

  # if '', There is no pre trained weights, else the name is in /Model_save/
  Pre_Trained_Weights: 'EfficientUnet3Plus5_200_epoch.h5'
  Module:
    CBAM: False

Predict:
  save_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/predict"
  Pre_Trained_Weights: 'EfficientUnet3Plus7_200_epoch.h5'