Image:
  Width: 320
  Height: 224



Train:
  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented"
  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented_mask"

  Epoch: 50
  Batch_Size: 8

  Model_Used: 'DeeplabV3Plus' # ['Unet', 'DeeplabV3', 'DeeplabV3Plus', 'EfficientUnet', 'EfficientUnet3Plus', 'EfficientUnet3Plus']

  # if '', There is no pre trained weights, else the name is in /Model_save/
  Pre_Trained_Weights: ''
  Module:
    Attention: ''   # CBAM or SE or nothing



Predict:
  save_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/predict"
  Pre_Trained_Weights: 'Unet_200_epoch.h5'



Models_Detail:
  DeeplabV3Plus:
    Backbone: 'Xception' # ['Xception', 'ResNet50']
  EfficientUnet3Plus:
    layers: 7 # 5 or 7