Train:
#  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Roboflow/v6/augmented"
#  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Roboflow/v6/augmented_mask"

  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Smart-Farm/augmented"
  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Smart-Farm/augmented_mask"

  Image:
    Width: 320
    Height: 224


  # class ---> RGB value
  # class = 2 means [0,0,1] in one-hot encoding
  Class_Map: {
           Background: [0, 0, 0],
           Leaf: [0, 255, 0],
           Stem: [238, 201, 0],
  }
#  Class_Map: {
#            Background: [0, 0, 0],
#            PotPlant: [255, 255, 255]
#  }

  Epoch: 200
  Batch_Size: 8

  # ['FCN', 'Unet', 'UNet3+', 'SegNet', 'RefineNet', 'DeeplabV3', 'DeeplabV3Plus', 'EfficientUnet', 'EfficientUnet3Plus','SETR']
  Model_Used: 'UNet3+'

  # if '', There is no pre trained weights, else the name is in /Model_save/
  Pre_Trained_Weights: ''



Predict:
  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Roboflow/v6/image"
  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm-All/Roboflow/v6/mask"
  save_path: "/Users/shijunshen/Desktop/pred/againnnnnnn"
  all: True # if True, predict all pics in save_path, else predict 10 pics.
  Pre_Trained_Weights: 'DeepLabV3_200.h5'



Models_Detail:
  Unet:
    Attention: ''
  DeeplabV3Plus:
    Backbone: 'ResNet50' # ['Xception', 'ResNet50']
  EfficientUnet3Plus:
    version: 0 # B0 - B7
    layers: 7 # 5 or 7
    ASPP: False
    Attention: '' # CBAM or SE or nothing
  EfficientUnet:
    version: 0 # B0 - B7