Image:
  Width: 320
  Height: 224



Train:
  image_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented"
  label_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/augmented_mask"

  Epoch: 50
  Batch_Size: 8

  # ['Unet', 'DeeplabV3', 'DeeplabV3Plus', 'EfficientUnet', 'EfficientUnet3Plus', 'EfficientUnet3Plus','SETR']
  Model_Used: 'SETR'

  # if '', There is no pre trained weights, else the name is in /Model_save/
  Pre_Trained_Weights: ''



Predict:
  save_path: "/Users/shijunshen/Documents/Code/dataset/Smart-Farm/predict"
  all: False # if True, predict all pics in save_path, else predict 10 pics.
  Pre_Trained_Weights: 'Eff7_ASPP_50_epoch.h5'



Models_Detail:
  DeeplabV3Plus:
    Backbone: 'Xception' # ['Xception', 'ResNet50']
  EfficientUnet3Plus:
    layers: 7 # 5 or 7
    ASPP: True
    Attention: '' # CBAM or SE or nothing